# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5yraUpgWmPy35p1FnsPUphqdsr5T0KZ

Preprocessing
"""

pip install pandas numpy nltk Sastrawi scikit-learn

import pandas as pd
import numpy as np
import re
import string

import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download('stopwords')

df = pd.read_csv('KS_scrap (1).csv')

# lihat isi
print(df.head())

df.columns

df['clean_text'] = df['full_text'].str.lower()

def clean_text(text):
    text = re.sub(r'http\S+|www\S+', '', text)  # hapus URL
    text = re.sub(r'@\w+', '', text)            # hapus mention
    text = re.sub(r'#\w+', '', text)            # hapus hashtag
    text = re.sub(r'\d+', '', text)             # hapus angka
    text = text.translate(str.maketrans('', '', string.punctuation))  # hapus tanda baca
    text = text.strip()
    return text

df['clean_text'] = df['clean_text'].apply(clean_text)

df['tokens'] = df['clean_text'].apply(lambda x: x.split())

from nltk.corpus import stopwords

# stopword indo
stop_words_id = set(stopwords.words('indonesian'))

# stopword inggris
stop_words_en = set(stopwords.words('english'))

# custom slang / noise
custom_stopwords = {
    'yg', 'aja', 'nih', 'sih', 'dong', 'nya', 'deh', 'kok', 'lah',
    'gue','lu','gw','bgt','ya','ga','gak',
    'of','in','and','to','the','it','that'  # jaga2 kalau lolos
}

# gabungkan semua
all_stopwords = stop_words_id.union(stop_words_en).union(custom_stopwords)

# apply ke token
df['tokens'] = df['tokens'].apply(
    lambda x: [word for word in x if word not in all_stopwords]
)

factory = StemmerFactory()
stemmer = factory.create_stemmer()

df['tokens'] = df['tokens'].apply(lambda x: [stemmer.stem(word) for word in x])

df['processed_text'] = df['tokens'].apply(lambda x: ' '.join(x))

print(df[['full_text', 'processed_text']].head())

df.head()

df.to_csv('hasil_preprocessing.csv', index=False)

"""Analisis Sentimen"""

pip install pandas transformers torch

import pandas as pd
from transformers import pipeline

# load data
df = pd.read_csv('hasil_preprocessing.csv')

# pastikan kolom teks
text_col = 'clean_text'  # ganti kalau beda

# load model multilingual sentiment
sentiment_model = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment"
)

def get_sentiment(text):
    try:
        result = sentiment_model(text[:512])[0]  # batasi panjang
        label = result['label']
        score = result['score']

        # konversi label
        stars = int(label[0])
        if stars <= 2:
            sentiment = 'negative'
        elif stars == 3:
            sentiment = 'neutral'
        else:
            sentiment = 'positive'

        return sentiment, score
    except:
        return 'error', 0

df[['sentiment', 'confidence']] = df[text_col].apply(
    lambda x: pd.Series(get_sentiment(str(x)))
)

print(df['sentiment'].value_counts())

import matplotlib.pyplot as plt

df['sentiment'].value_counts().plot(kind='bar')
plt.title("Distribusi Sentimen")
plt.show()

df.head()

df.to_csv('hasil_sentiment_multilingual.csv', index=False)

"""Bigram & Trigram"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv('hasil_preprocessing.csv')

text_col = 'processed_text'

df[text_col] = df[text_col].fillna('')

bigram_vectorizer = CountVectorizer(ngram_range=(2,2), min_df=2)

bigram_matrix = bigram_vectorizer.fit_transform(df[text_col])

bigram_counts = bigram_matrix.sum(axis=0)

bigram_freq = [(word, bigram_counts[0, idx])
               for word, idx in bigram_vectorizer.vocabulary_.items()]

bigram_freq = sorted(bigram_freq, key=lambda x: x[1], reverse=True)

# tampilkan top 20
print("Top Bigram:")
for i in bigram_freq[:20]:
    print(i)

trigram_vectorizer = CountVectorizer(ngram_range=(3,3), min_df=2)

trigram_matrix = trigram_vectorizer.fit_transform(df[text_col])

trigram_counts = trigram_matrix.sum(axis=0)

trigram_freq = [(word, trigram_counts[0, idx])
                for word, idx in trigram_vectorizer.vocabulary_.items()]

trigram_freq = sorted(trigram_freq, key=lambda x: x[1], reverse=True)

# tampilkan top 20
print("\nTop Trigram:")
for i in trigram_freq[:20]:
    print(i)

bigram_df = pd.DataFrame(bigram_freq, columns=['bigram', 'count'])
trigram_df = pd.DataFrame(trigram_freq, columns=['trigram', 'count'])

bigram_df.to_csv('bigram.csv', index=False)
trigram_df.to_csv('trigram.csv', index=False)

"""Wordcloud

"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

text = ' '.join(df['processed_text'])

wc = WordCloud(width=800, height=400, background_color='white').generate(text)

plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.title("WordCloud Keseluruhan")
plt.show()

bigram_text = ' '.join([word for word, count in bigram_freq[:100]])

wc = WordCloud(width=800, height=400, background_color='white').generate(bigram_text)

plt.imshow(wc)
plt.axis('off')
plt.title("WordCloud Bigram")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

top_bigram = pd.DataFrame(bigram_freq[:10], columns=['bigram','count'])

top_bigram.plot(kind='barh', x='bigram', y='count')
plt.title("Top 10 Bigram")
plt.gca().invert_yaxis()
plt.show()

"""Network Analysis"""

pip install networkx matplotlib

import networkx as nx
import matplotlib.pyplot as plt

# ambil top 50
top_bigrams = bigram_freq[:50]

G = nx.Graph()

for bigram, count in top_bigrams:
    word1, word2 = bigram.split()
    G.add_edge(word1, word2, weight=count)

plt.figure(figsize=(10,8))

pos = nx.spring_layout(G, k=0.5)

nx.draw(
    G, pos,
    with_labels=True,
    node_size=2000,
    font_size=10
)

# kasih label weight (opsional)
edge_labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

plt.title("Network Bigram")
plt.show()

weights = [G[u][v]['weight'] for u,v in G.edges()]

plt.figure(figsize=(10,8))
pos = nx.spring_layout(G, k=0.5)

nx.draw(
    G, pos,
    with_labels=True,
    node_size=1500,
    width=weights,   # garis lebih tebal = lebih sering
    font_size=10
)

plt.title("Network Bigram (Weighted)")
plt.show()

"""Centrality Analysis"""

centrality = nx.degree_centrality(G)

# top 5 kata paling penting
sorted(centrality.items(), key=lambda x: x[1], reverse=True)[:5]

"""Analysys Further"""

df = pd.read_csv('hasil_sentiment_multilingual.csv')

sent_dist = df['sentiment'].value_counts(normalize=True) * 100
print(sent_dist)

neg_text = df[df['sentiment']=='negative']['processed_text']

print(neg_text)

"""Gap Analysis"""

neg_df = df[df['sentiment'] == 'negative']

keluhan_keywords = [
    'takut', 'trauma', 'korban', 'pelecehan', 'tidak', 'aman'
]

solusi_keywords = [
    'lapor', 'polisi', 'hukum', 'tindak', 'bantu', 'lindung'
]

print(neg_df[neg_df['processed_text'].isna()])

df['processed_text'] = df['processed_text'].fillna('').astype(str)
df = df[df['processed_text'].str.strip() != '']

from collections import Counter

all_words = ' '.join(neg_df['processed_text']).split()
word_counts = Counter(all_words)

keluhan_count = sum([word_counts[k] for k in keluhan_keywords if k in word_counts])
solusi_count = sum([word_counts[k] for k in solusi_keywords if k in word_counts])

print("Keluhan:", keluhan_count)
print("Solusi:", solusi_count)

import matplotlib.pyplot as plt

labels = ['Keluhan', 'Solusi']
values = [keluhan_count, solusi_count]

plt.bar(labels, values)
plt.title("Gap Keluhan vs Solusi (Sentimen Negatif)")
plt.show()

"""Topic Modelling"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_df=0.9, min_df=5)
X = vectorizer.fit_transform(df['processed_text'])

from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_components=3, random_state=42)
lda.fit(X)

words = vectorizer.get_feature_names_out()

for idx, topic in enumerate(lda.components_):
    print(f"\nTopik {idx+1}:")
    print([words[i] for i in topic.argsort()[-10:]])